name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Install node"
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm i
      - run: npm run test
